### ISSUE TITLE
Make Drupal 8 the default

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#108]
We have now been using Drupal 8 by default for new projects for over a year, it would be good to reflect that and make it the default in Wundertools.

Proposed steps:
- Move the current Drupal 7 code to a dedicated branch
- Promote the Drupal 8 branch to main branch (or merge it to master?)
- Apply changes to align Wundertools with general Drupal 8 practices (more details in specific issues)
- Clean up code and documentation specific to Drupal 7

**Comment by tharna** [comment]
Definitely. Once the structure is aligned with proper composer / drupal standards we can make the switch.
Requires #109

**Comment by tharna** [comment]
Composer branch is the basis of this and once all tasks are resolved it will be promoted as a new master.
