### ISSUE TITLE
Build Drupal 8 projects with a standard composer approach

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#109]
The Drupal-Composer project template (https://github.com/drupal-composer/drupal-project) has been adopted as the standard, both within our project teams and the general Drupal community. It also aligns quite well with common practices in the PHP community. 

Rather than using the code-generation built into the Drupal-Composer, it probably makes sense to start with the generated structure (which gets committed to code git anyways).

```
/ <-- project root
/drupal/ <-- Drupal-specific code
/drupal/composer.json
/drupal/composer.lock
/drupal/vendor <-- third-party PHP libraries, gets populated by composer
/drupal/web/index.php <-- web root
/drupal/web/modules/contrib/ <-- empty folders, gets popuplated by composer
/drupal/web/modules/custom/ <-- custom code, committed to repository
```

For productive deployment it makes sense for the webroot to be a symlink pointing to the latest successful deployment, but it's really a lot more practical for local environments to build in place.

**Comment by tharna** [comment]
Production should never use symlinks.
Local build could be made with simple composer run, or build.sh can be used if there are any additional tasks needed to setup the app. The production deployment needs a bit more work to work with this structure.
Also having custom code "in place" makes gitignore a bit more complex to manage.

**Comment by tharna** [comment]
There is now dedicated branch for this called composer. Let's work on that as a base branch for any features related to this update.
