### ISSUE TITLE
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory

### ISSUE THREAD

**Issue by hkirsman** [wunderkraut/WunderTools#11]
After clean install and logging into the box (vagrant ssh), I get this notice in the bash:
``` sh
-bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
```

**Comment by james-nesbitt** [comment]
do you have either of these environment variables:

````
LANG=en_US.UTF-8
LC_CTYPE=en_US.UTF-8
````

To find out try
````
$/> export | grep LANG
````

This is either a configuration failure of the logged in user, or a failure to build the UTF8 locale during build.  The latter is unlikely, as the box should be prebuilt with the values.

if you have the variables, can you tell me the contents of any of the following files (different files exist on different distros):
````
/etc/default/locale
/etc/locale.conf
````

**Comment by hkirsman** [comment]
I don't have them set on my mac but LANG is set in the WunderTools centos 7 branch
    hannes@wunder:~/Sites/opencampus|centos7⚡
    ⇒  export | grep LANG
    hannes@wunder:~/Sites/opencampus|centos7⚡
    ⇒  vagrant ssh
    Last login: Mon Mar 14 11:42:37 2016 from 10.0.2.2
    -bash: warning: setlocale: LC_CTYPE: cannot change locale (UTF-8): No such file or directory
    [vagrant@opencampus ~]$ export | grep LANG
    declare -x LANG="en_US.UTF-8"

**Comment by hkirsman** [comment]
I just noticed that the error happens on my iTerm2 and not in PhpStorm terminal.

**Comment by aleksijohansson** [comment]
I think this is an issue with the host configuration, not WunderTools.
