### ISSUE TITLE
Clarify the "conf" folder

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#110]
The "conf" folder currently contains 14 files, with no clear relationship between them. It would be useful to separate those that affect any environments and then those that affect a specific environments.

**Comment by tharna** [comment]
Separating those confs would make provisioning scripts more complex and the fact that normal dev probably doesn't need to worry about those that often I think this is not needed or at least not high priority.

**Comment by floretan** [comment]
Sorry, the discussion was actually meant to be about the "conf" folder inside of the drupal folder and I got confused.
