### ISSUE TITLE
Make PHP7 the default

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#111]
PHP 7 provides some nice performance benefits and it is now stable. It makes sense to use it as the default for new projects.

**Comment by badrange** [comment]
Agree. I think one thing that has kept the change to PHP7 back is the lack of memcache support - but that is now available as of last week or so.

**Comment by tharna** [comment]
@badrange need to check that out.
In any case d8 is much more efficient with caching in general, so in most cases memcache wouldn't even be that critical. However some apps might still benefit from memcache.

**Comment by floretan** [comment]
Some of the benchmarks showed that memcache wasn't noticeably faster than the built-in database cache, and as far as I know none of our D8 projects actually make use of memcache. Redis has also been gaining a lot more traction, but that's a different issue. I would be fine not having memcache or redis by default for D8 projects.

**Comment by hugovk** [comment]
PR https://github.com/wunderkraut/WunderTools/pull/112 has been merged, this can be closed.

**Comment by tharna** [comment]
It's only merged to the composer branch. Which will eventually become new master and default. 
So this is kinda resolved, but not yet default :D

**Comment by floretan** [comment]
Agreed.
