### ISSUE TITLE
Build status badge points into wrong repository in gh-pages

### ISSUE THREAD

**Issue by onnimonni** [wunderkraut/WunderTools#113]
Currently the frontpage of the [project documentation](http://wundertools.wunder.io/#!index.md) looks like this:

<img width="1328" alt="screen shot 2017-03-09 at 4 41 16 pm" src="https://cloud.githubusercontent.com/assets/5691777/23754978/9502109c-04e7-11e7-998c-20843a98395d.png">

It seems that this repository was renamed from **wunderkraut/WunderMachina** -> **wunderkraut/WunderTools** but all references to old project name were not fixed.

I'll submit a PR soon.

**Comment by hugovk** [comment]
Looks fine for me:

![image](https://cloud.githubusercontent.com/assets/1324225/23759144/8ee5aeb4-04f4-11e7-8d34-34902f5532f9.png)

It's pointing to this file: https://travis-ci.org/wunderkraut/WunderMachina.svg?branch=centos7

But a repo name change would make sense.

**Comment by onnimonni** [comment]
It was actually broken only because I use [privacy badger browser plugin](https://www.eff.org/privacybadger). It blocks requests to travis by default and I should have seen that. Luckily this helped me to find out that the build badge still links to a wrong repository.

<img width="381" alt="screen shot 2017-03-09 at 7 46 54 pm" src="https://cloud.githubusercontent.com/assets/5691777/23763159/31afabc0-0501-11e7-96cc-77fc699acec5.png">
