### ISSUE TITLE
Use the example settings.local.php

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#119]
Drupal 8 provides a file called example.settings.local.php in `web/sites/`, which overrides the active configuration with everything needed for a painless local development setup. This file is meant to be moved to `web/sites/settings.local.php` (excluded from repository) and included from the bottom of `web/sites/default/settings.php`. 

Can we automate this step?

**Comment by tharna** [comment]
I would still vote for single settings.php approach as defined in #115.
We often have additional things we might to add to local configs anyway so would make sense to have those in repository. Otherwise we end up having local configs scattered all around and duplicating common configs across environments as has been happening so far when we have been using [env].settings.php files.

**Comment by onnimonni** [comment]
I would propose to use one central `conf/settings.php` which contains the basic shared settings for all environments and smaller settings files for different environments which can be included in the main `settings.php`

For example `conf/environments/development.php` could look like this:
```
<?php
/**
 * These directives are included in for local development environment
 */

// Use verbose logging in development to help debugging
$config['system.logging']['error_level'] = env('DRUPAL_LOGGING_ERROR_LEVEL') ?: 'verbose';
```
This way we can override settings but they will have sane default values.

**Comment by floretan** [comment]
I would rather not combine two different possible ways of doing overrides. Either we put references to environment variables in settings.php and set these based on the environment, or we include different additional files. I wouldn't use environment variables in an already environment-specific file.

What I could see is using environment variables for things that need to be specified in every environment, like database credentials. Using settings.local.php has pretty much become an established standard, but only for local development environments, and we could use it just for that. The example.settings.local.php has settings specifically addressing an environment in which the project code is being edited, so in most cases it doesn't make sense to use these settings in any hosted environment.

**Comment by tharna** [comment]
I would suggest we include everything that is shared between environments in the settings.php. This includes all the configuration options needed for those environments even if the values vary. For the values environment variables will be used.
If there are any environment specific configs (for example those developer options) those would then be included from the optional environment specific config file ([envi].settings.php)

**Comment by tharna** [comment]
settings.local.php is now used by default on local. There is a separate issue about using env_vars
