### ISSUE TITLE
Move Drupal-specific configuration files 

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#120]
With an in-place deployment for local environments, all Drupal-specific configuration files can be moved from ´drupal/conf´ to their final location, leaving only WudnderTools-specific code in that folder.

**Comment by tharna** [comment]
There is only settings.local and vagrant.settings left. Need to resolve #115 to make this fully working solution.

**Comment by tharna** [comment]
I'll close this as only the settings issue remains and it has it's own separate issue.
