### ISSUE TITLE
Remove support for drush make

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#122]
Drush make has served us well up to Drupal 7, but it has become obsolete for Drupal 8 and future projects. We can remove all code and documentation related to it.

**Comment by tharna** [comment]
There might still be others using d7 so let's not start removing working functionality.

**Comment by floretan** [comment]
D7 users would use the Drupal 7 branch, there is no use for drush make in the D8 branch. 

Removing support for drush make would simplify build.sh, site.yml and commands.yml a lot. These are the files that people actually interact with – and also the ones people find confusing.

**Comment by tharna** [comment]
That would lead us maintaining 2 versions of build.sh and also old projects would need to be updated.
Let's review this again if we end up choosing to continue with build.sh anyway. Otherwise we would just be wasting a lot of time here.

**Comment by floretan** [comment]
Closing after discussion with @tharna. Build.sh won't be updated, instead we'll look for an alternative as mentioned in #117.
