### ISSUE TITLE
Enable APCu by default

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#125]
Drupal 8 can take advantage of APCu out of the box (see https://www.drupal.org/node/2327507), it would make sense to have the PHP extension enabled by default.

**Comment by onnimonni** [comment]
Just wanted to add my 2 cents here.

APCu might be the best option and I don't have much experience in Drupal. I have tested and compared these a lot with WordPress setups and over there redis has similar performance and it's much more easier to invalidate data in the object cache when running multiple php/drupal/wordpress instances in clustered setups (eg. AWS autoscaling groups).

I googled this a bit and this seems to be true for drupal too:
> ... if you multiple PHP frontends, each frontend will carry its own shared memory, data in those frontends may differs: this means that you can have a cache desync between PHP frontends; That's why we oftenly prefer to use a memcache, or redis or mongodb.
> https://www.drupal.org/node/2384639

This seems to be the prefered module for redis:
https://www.drupal.org/project/redis

**Comment by tharna** [comment]
Yes, multiserver setups have been the reason we have been sticking with memcached in the past. When that decision was made Redis too had similar issues as APCu on those setups. Now I think Redis has evolved from those days and could be a viable option. Memcached finally also seems to have php 7 version out, but still it's support is not guaranteed.

**Comment by floretan** [comment]
The cache.backend.chainedfast plugin which is used by default only saves cache data that can be rebuilt deterministically into APCu, everything else gets passed on to the database cache. We could even use the same multi-tiered approach with APCu for the local cache and redis/memcache for the central cache. Also worth having a look at is https://www.drupal.org/project/lcache.

**Comment by tharna** [comment]
Tiered cache sounds fantastic (and a nightmare).
In any case we could definitely enable APCu out of the box. I'll move this ticket over to WunderMachina.
