### ISSUE TITLE
Make ping.php a composer package

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#126]
If we make ping.php a composer package, then we can add it to the installation process without having one loose file that needs to be copied.

**Comment by tharna** [comment]
This is an interesting idea which would also allow us to have ping.php updates handled in centralized manner.
Any way if the copying is the only issue latest versions already have it in place.

**Comment by mgalang** [comment]
Great suggestion. If I may add, some projects have custom stuff in their ping.php, but this could be resolved by add an include() to a local file if it exists so we could add customisation when needed.

**Comment by tharna** [comment]
Resolved by #187 
Will add the include feature request to our new ping repo
