### ISSUE TITLE
Move drush site aliases to ../drush

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#136]
Drush site aliases are now recognized automatically in a `drush` folder one level above the web root (see https://github.com/drush-ops/drush/blob/master/examples/example.aliases.drushrc.php). We should follow this convention, this also means we would have one less file in the Drupal-specific `conf` folder.

**Comment by tharna** [comment]
Project build.sh should be updated to reflect this change. It assumes aliases file to be found under drupal/conf when linking it.
