### ISSUE TITLE
More useful location when ssh-ing to vagrant (was: Nice to have)

### ISSUE THREAD

**Issue by hkirsman** [wunderkraut/WunderTools#14]
Would like to cd automatically to /vagrant/drupal/current/  every time I log in. That's the location I want to go to most of the time after system is running. And maybe create the folder automatically after first vagrant up?

**Comment by james-nesbitt** [comment]
doesn't /vagrant/drupal/current get built by drush make?  if so then it cannot exist when drush make is run.  Would starting in /vagrant/drupal be sufficient? or do you really want to start in the Drupal root?

Is this so that you can run drush?

**Comment by hkirsman** [comment]
You are probably right.
Would it make sense to cd to /vagrant/drupal if /vagrant/drupal/current does not exist?

Yes sometimes I've run drush commands there. Need to get used to aliases.
But I guess what I mean is that I rarely want to do something in /home/vagrant.

**Comment by badrange** [comment]
@hkirsman At least know this: Drush aliases are now created automatically for you, so if you want to go to the current-folder, all you need to do is to type the "super short" ```drush @reallylongprojectname.local ssh``` and you'll see yourself right where you wanted to be.

**Comment by hkirsman** [comment]
Great tip!

**Comment by aleksijohansson** [comment]
@hkirsman Maybe this could be closed since there is an alternative?

**Comment by tharna** [comment]
I don't see the point spending our time dublicating functionality provided by other tools.
