### ISSUE TITLE
Resources not loaded because of the security violation

### ISSUE THREAD

**Issue by hkirsman** [wunderkraut/WunderTools#15]
No js, css or image are loaded. Getting errors in browser:
_Refused to load the image 'http://drupal7.dev/misc/favicon.ico' because it violates the following Content Security Policy directive: "default-src https: data: 'unsafe-inline' 'unsafe-eval'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback._

Because I remove the ssl part of roles in vagrant.yml:
```
#   - { role: letsencrypt, tags: [ 'letsencrypt' ] }
#   - { role: sslterminator, tags: [ 'sslterminator' ] }
```
I would expect the nginx.conf be adjusted accordingly.

Grepping the code gives:
```
grep -rni default-src .
./ansible/playbook/roles/nginx/templates/nginx.conf.j2:68:  add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'" always;
./ansible/playbook/roles/sslterminator/templates/nginx.conf.j2:68:  add_header Content-Security-Policy "default-src https: data: 'unsafe-inline' 'unsafe-eval'" always;
```
So I understand that it would be safe to remove it from /ansible/playbook/roles/nginx/templates/nginx.conf.j2 as it's exists in /ansible/playbook/roles/sslterminator/templates/nginx.conf.j2 ?

**Comment by iler** [comment]
IMO there are two things here:

1. We could split and re-arrange those nginx related roles a bit to reduce duplicate stuff
2. We should use https on local dev too to have it as close as possible to prod

@tharna do you agree with these?

**Comment by hkirsman** [comment]
I totally agree with you on your 2'nd statement but  shouldn't the Ansible roles work separately from each other? So for example I didn't need Varnish and I disabled that from the conf/vagrant.yml. So I would assume that there are no Varnish configurations in the other roles and the provision would not break.

**Comment by iler** [comment]
@hkirsman that's why I mentioned the first point :)

**Comment by iler** [comment]
@hkirsman and these changes are actually something that needs to be done here https://github.com/wunderkraut/WunderMachina/tree/centos7

**Comment by hkirsman** [comment]
my bad :)

**Comment by aleksijohansson** [comment]
@hkirsman This seems to be fixed in the latest commits to the master branch, maybe this issue can now be closed?
