### ISSUE TITLE
HHVM support

### ISSUE THREAD

**Issue by hkirsman** [wunderkraut/WunderTools#16]
There's interest in adding HHVM into the WunderTools (probably optionally?). As I don't see any packages specifically for CentOS at https://docs.hhvm.com/hhvm/installation/introduction#prebuilt-packages then I guess we need to build it? I'm currently using this docs https://github.com/facebook/hhvm/wiki/Building-and-installing-hhvm-on-CentOS-7.x for building. It takes time (I mean I have waited like 15 minutes and it's still at 44%)... and it needs all these extra packages installed in Linux. Maybe we should add extra repo for HHVM where it's already built? There are so many things that could wrong with build. Would not want to add that hassle to WunderTools installation.

Edit
Quote from https://ckon.wordpress.com/2014/07/18/hhvm-centos-7/:
Note that unlike PHP/PHPNG, HHVM requires major resources to build. You may be used to making PHP in 15 minutes on a little old 256mb 1ghz box. You can forget that with HHVM which is a beast to compile. 1gb ram minimum and lots of cpu power required to keep it an hour or two (this is part of why PHP NG instead is so exciting because it will be so much easier to custom build).

**Comment by hkirsman** [comment]
Moved to https://github.com/wunderkraut/WunderMachina/issues/13

**Comment by tharna** [comment]
Option to use HHVM added to centos7 branch with instructions.
