### ISSUE TITLE
Enable xdebug by default on local environments

### ISSUE THREAD

**Issue by floretan** [wunderkraut/WunderTools#174]
We want to encourage developers to use xdebug. Even though it has a small negative impact on performance, that is offset by the benefits of having xdebug enabled by default for local environments.

**Comment by evilfurryone** [comment]
When I was previously using Ubuntu I had this very strange issue where having xdebug enabled basically froze the local environment for whatever site I was using. Every php action (even be it some simple drush commands) took 2 minutes to complete. Solution was to remove xdebug. This was a problem that I only seemed to have as anyone else responding to my calls for help could not replicate it. 

By fully enabling it on all boxes we might get few more people having similar issues who just did not comment on the matter earlier.
