### ISSUE TITLE
docs/content_types.md should be docs/information_architecture.md

### ISSUE THREAD

**Issue by goechsler** [wunderkraut/WunderTools#19]
Hi,

Where should I describe my relations? Where do my taxonomies go? 

Rather than just describing a list of content types, we should use a information architecture document which sketches out all they "entities" in place and how they play together.

Cheers,
Georg

**Comment by tharna** [comment]
Definitely a good idea. Those are just a basic templates and maybe there are some simplle sites with just couple of content types without any more complex relationships. For the more complex ones it can always be extended and it might be even necessery that the site is so complex that both could be documented separately.

Feel free to create a pull request with a default IA template to get started :)
Thanks,
-Janne
