### ISSUE TITLE
Plan to upgrade Ansibleref to Centos 7

### ISSUE THREAD

**Issue by joesb** [wunderkraut/WunderTools#2]
Will need several changes:

- [x] Packaged Varnish is v4, so need to update vcl etc.
- [ ] Packaged Nginx includes SPDY support, so consider updating vhost configs with SPDY
- [ ] Packaged PHP is 5.4.x, so support for alternatives will need to be added
- [x] Mailcatcher install from Centos 6.x Ansibleref doesn't seem to work on 7, so consider MailHog cf. #1 
- [x] Update Ansibleref my.cnf to work with MariaDB 10.x

Maybe more besides?

**Comment by aleksijohansson** [comment]
Really glad to see someone properly suggesting this! I've heard we have a project already on Varnish 4, so could get vcl from it

**Comment by iler** [comment]
- Nginx: We already have working version of Nginx SPDY configs that are already used in production. However we have found some problems when using Nginx 1.8.x branch which is the current stable for Nginx. Nginx 1.6 works without problems though.
- PHP: We are already using PHP 5.5 on new installations and should start using PHP 5.6 as soon as we have tested it. Security updates for PHP 5.4 will end on 14th of September 2015 and for PHP 5.5 10th of July 2016.
- MariaDB: We need to update our my.cnf to work on MariaDB 10.0.x. Our current version of my.cnf that is made for 5.5.x has performance problems when used with 10.0.x.

**Comment by joesb** [comment]
JAC project is deployed on Centos 7 with Varnish 4, and I had to fiddle around with the vcl there to get it working.
This is the vcl I used.
https://gist.github.com/joesb/9cee60b9b4b800b838f3

**Comment by tharna** [comment]
@joesb care to throw anything useful from JAC to a new centos7 branch as a basis for us to start working on this? Would probably give us a nice head start on this :)

**Comment by tharna** [comment]
And btw. most of this should be in the WunderMachina anyway ;)

**Comment by joesb** [comment]
I don't think I'd quite realised that [wunderkraut/WunderMachina](https://github.com/wunderkraut/WunderMachina) is the place for the Ansible stuff. I'll interact over there.

Yes, I did a fair bit of stuff on the Centos7 version of the JAC machine, so I may be able to add a bunch o' stuff from there.

**Comment by tharna** [comment]
There is centos7 branch of Wundermachina that should be now default branch. But before we can make it to the master we need to upgrade / ensure old projects using centos6 will continue working.

**Comment by aleksijohansson** [comment]
@tharna Since centos7 is now master, maybe this issue could be closed?
