### ISSUE TITLE
Create support/variant/branch for Drupal 8 sites

### ISSUE THREAD

**Issue by joesb** [wunderkraut/WunderTools#3]
Drupal 8 for production is coming closer to a reality. Would be good to have an install variant that supports Drupal 8 dev work.

**Comment by joesb** [comment]
What do we need to do to support Drupal 8 in Ansibleref other than drush version? Anything?

**Comment by aleksijohansson** [comment]
There is a lot of D7 specifics in the Nginx confs so those need to be checked at least.

**Comment by iler** [comment]
@tcmug I remember you had already done something related to D8?

**Comment by tharna** [comment]
There is already d8 branch for this. Feel free to test / work on it :)

**Comment by aleksijohansson** [comment]
Drupal 8 branch can be found here: https://github.com/wunderkraut/WunderTools/tree/d8

Closing the issue.
