### ISSUE TITLE
Support for dry-run in provision.sh

### ISSUE THREAD

**Issue by badrange** [wunderkraut/WunderTools#45]
If it has been a while since last provision, or if you're about to provision something to a server you don't know that well, it may scary to do a provision since you're not sure about what is going to happen. 

Would be great if we could do a dry run before the actual run!

**Comment by badrange** [comment]
I'm thinking about these flags to ansible-playbook: 
`  -C, --check           don't make any changes; instead, try to predict some
                        of the changes that may occur`
and
`  -D, --diff            when changing (small) files and templates, show the
                        differences in those files; works great with --check`

**Comment by tharna** [comment]
The -v issue still remains

**Comment by tharna** [comment]
Changed vault_pass flag into p in #66 to allow passing -v flag.
