### ISSUE TITLE
Make ansible vault file optional in provision.sh

### ISSUE THREAD

**Issue by tharna** [wunderkraut/WunderTools#71]
It should be possible to provision without the need for ansible vault password file.
Currently even if you don't use ansible-vault you need to provide vault password file for provision.sh.

Workaround for now:
```
$ touch ansible_vault_pass
$ export WT_ANSIBLE_VAULT_FILE=ansible_vault_pass
```
@badrange

**Comment by badrange** [comment]
Thanks! I suppose only the people provisioning servers have been using provision.sh until now; and yes making it usable for vagrant-only-developers is a great plus!
