### ISSUE TITLE
Create example on how to use multicore SOLR available in WunderMachina

### ISSUE THREAD

**Issue by aleksijohansson** [wunderkraut/WunderTools#76]
Related to this https://github.com/wunderkraut/WunderMachina/issues/96 we should add an example to WunderTools on how a project can use multicore SOLR. This is specifically needed because we should use the SOLR config from search_api_solr module that the project is using so it needs to be done on the project level and can't be predefined. See https://ohthehugemanatee.org/blog/2013/04/18/how-to-set-up-apache-solr-multicore-for-drupal/

**Comment by artursv** [comment]
@aleksijohansson Would it be enough to have an example multicore role people can copy/modify? I created something for my project so we could use that.

**Comment by tharna** [comment]
@artursv would be nice to have support for multicore directly in the playbook. But for the starters I think the multicore example as local role would be enough to get started.

**Comment by floretan** [comment]
Closing as this issue hasn't been touched in a while and we are looking at using Elasticsearch even for Drupal 7 projects. Feel free to reopen if needed.
