### ISSUE TITLE
Drush sql-drop before sql-sync

### ISSUE THREAD

**Issue by forgenator** [wunderkraut/WunderTools#90]
Due to the nature of sql-sync not actually deleting tables/database when running sql-sync there is the possibility of stale database-tables being left inside the database when doing development between multiple branches and creating/deleting fields.

This can be fixed by adding drush sql-drop before we sync production database. This way the actual development procedure is:

* start new feature branch
* run sync.sh
* <do stuff>
* commit and push

* Rinse-and-repeat. 

This way if we create new fields and then jump back to different branches there is no way of having field -data inside the database that shouldn't be there.

**Comment by badrange** [comment]
+1 to this! I've even had it in some sync scripts (and never gotten around to push upstream).

**Comment by aleksijohansson** [comment]
This was fixed by the new syncdb.sh script in #106.
